# Generated by Django 3.2 on 2021-12-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
