# Generated by Django 3.2 on 2021-12-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-answered_on']},
        ),
    ]
