# Generated by Django 3.2 on 2021-12-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_on']},
        ),
    ]
